const CELSIUS_VERY_COLD = 0
const CELSIUS_COLD = 10
const CELSIUS_MILD = 20
const CELSIUS_WARM = 25

const TEMPERATURE_LIMITS = {
  VERY_COLD: CELSIUS_VERY_COLD,
  COLD: CELSIUS_COLD,
  MILD: CELSIUS_MILD,
  WARM: CELSIUS_WARM,
} as const

const TEMPERATURE_SCALE = [
  "🥶",
  "🧥",
  "👕",
  "🩳",
  "🥵",
] as const

export const useTemperature = () => {
  return {
    temperatureScale: TEMPERATURE_SCALE,
    TEMPERATURE_LIMIT_VERY_COLD: TEMPERATURE_LIMITS.VERY_COLD,
    TEMPERATURE_LIMIT_COLD: TEMPERATURE_LIMITS.COLD,
    TEMPERATURE_LIMIT_MILD: TEMPERATURE_LIMITS.MILD,
    TEMPERATURE_LIMIT_WARM: TEMPERATURE_LIMITS.WARM,
  }
}
